### ISSUE TITLE
How to use this framework?

### ISSUE THREAD

**Issue by Kamuli** [google/open-location-code-swift#2]
Hi,
Problems with using this at objective-c project on High Sierra, Xcode 9.4 beta:

ld: warning: ignoring file .../OpenLocationCode.framework/OpenLocationCode, file was built for arm64 which is not the architecture being linked (x86_64): .../OpenLocationCode.framework/OpenLocationCode
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC16OpenLocationCode7OLCArea", referenced from:
      objc-class-ref in DetailViewController.o
  "_OBJC_CLASS_$__TtC16OpenLocationCode12OLCConverter", referenced from:
      objc-class-ref in DetailViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WilliamDenniss** [comment]
Are you using CocoaPods? It should be a simple as including OpenLocationCodeFramework in your Podfile, then importing with `@import OpenLocationCode;`
